- name: Install RKE and Configure Kubernetes Cluster
  hosts: all
  become: true
  tasks:
    - name: Add Docker repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Python 3 and dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install RKE via pip
      pip:
        name: "rke"

    - name: Initialize Kubernetes Cluster with RKE
      command: rke up
      args:
        chdir: /path/to/your/rke/config/directory